{"uuid": "c85d667c-92f1-438b-b102-89f7f93ebbe9", "children": ["d1c96042-fc66-4702-b5c5-3d61830947da"], "befores": [{"name": "login_to_personal", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff71ab56f65+78965]\n\tGetHandleVerifier [0x0x7ff71ab56fc0+79056]\n\t(No symbol) [0x0x7ff71a8e9dda]\n\t(No symbol) [0x0x7ff71a8c20d1]\n\t(No symbol) [0x0x7ff71a96ff4e]\n\t(No symbol) [0x0x7ff71a9906cd]\n\t(No symbol) [0x0x7ff71a968443]\n\t(No symbol) [0x0x7ff71a931311]\n\t(No symbol) [0x0x7ff71a9320a3]\n\tGetHandleVerifier [0x0x7ff71ae0e26d+2926461]\n\tGetHandleVerifier [0x0x7ff71ae08993+2903715]\n\tGetHandleVerifier [0x0x7ff71ae26aed+3026941]\n\tGetHandleVerifier [0x0x7ff71ab716fe+187406]\n\tGetHandleVerifier [0x0x7ff71ab796ef+220159]\n\tGetHandleVerifier [0x0x7ff71ab5faf4+114692]\n\tGetHandleVerifier [0x0x7ff71ab5fca9+115129]\n\tGetHandleVerifier [0x0x7ff71ab464d8+10728]\n\tBaseThreadInitThunk [0x0x7ffcaf5c7374+20]\n\tRtlUserThreadStart [0x0x7ffcb055cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_item\\test_personal.py\", line 36, in login_to_personal\n    page.enter_username(DateDriver().username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\login_page.py\", line 14, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 65, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1752578553294, "stop": 1752578555455}], "start": 1752578553294, "stop": 1752578555692}