{"uuid": "cefd8403-a568-477e-a777-6abdbaa339f6", "children": ["f23e5d3e-ed7b-4c6a-a863-d0b99594a6bf"], "befores": [{"name": "login_to_module", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff641306f65+78965]\n\tGetHandleVerifier [0x0x7ff641306fc0+79056]\n\t(No symbol) [0x0x7ff641099dda]\n\t(No symbol) [0x0x7ff6410720d1]\n\t(No symbol) [0x0x7ff64111ff4e]\n\t(No symbol) [0x0x7ff6411406cd]\n\t(No symbol) [0x0x7ff641118443]\n\t(No symbol) [0x0x7ff6410e1311]\n\t(No symbol) [0x0x7ff6410e20a3]\n\tGetHandleVerifier [0x0x7ff6415be26d+2926461]\n\tGetHandleVerifier [0x0x7ff6415b8993+2903715]\n\tGetHandleVerifier [0x0x7ff6415d6aed+3026941]\n\tGetHandleVerifier [0x0x7ff6413216fe+187406]\n\tGetHandleVerifier [0x0x7ff6413296ef+220159]\n\tGetHandleVerifier [0x0x7ff64130faf4+114692]\n\tGetHandleVerifier [0x0x7ff64130fca9+115129]\n\tGetHandleVerifier [0x0x7ff6412f64d8+10728]\n\tBaseThreadInitThunk [0x0x7ffe68f47374+20]\n\tRtlUserThreadStart [0x0x7ffe691dcc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_module.py\", line 48, in login_to_module\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 33, in login\n    self.enter_password(password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 20, in enter_password\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入密码\"]', password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1760673482601, "stop": 1760673488647}], "start": 1760673482601, "stop": 1760673488780}