{"uuid": "eef38edb-3b49-4759-bfc3-74ce873b31dd", "children": ["edf0ccee-519a-4125-8e65-a05aecf7e3b0"], "befores": [{"name": "login_to_home", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff7f9df6f65+78965]\n\tGetHandleVerifier [0x0x7ff7f9df6fc0+79056]\n\t(No symbol) [0x0x7ff7f9b89dda]\n\t(No symbol) [0x0x7ff7f9b75bc5]\n\t(No symbol) [0x0x7ff7f9b9ac04]\n\t(No symbol) [0x0x7ff7f9c10195]\n\t(No symbol) [0x0x7ff7f9c306cd]\n\t(No symbol) [0x0x7ff7f9c08443]\n\t(No symbol) [0x0x7ff7f9bd1311]\n\t(No symbol) [0x0x7ff7f9bd20a3]\n\tGetHandleVerifier [0x0x7ff7fa0ae26d+2926461]\n\tGetHandleVerifier [0x0x7ff7fa0a8993+2903715]\n\tGetHandleVerifier [0x0x7ff7fa0c6aed+3026941]\n\tGetHandleVerifier [0x0x7ff7f9e116fe+187406]\n\tGetHandleVerifier [0x0x7ff7f9e196ef+220159]\n\tGetHandleVerifier [0x0x7ff7f9dffaf4+114692]\n\tGetHandleVerifier [0x0x7ff7f9dffca9+115129]\n\tGetHandleVerifier [0x0x7ff7f9de64d8+10728]\n\tBaseThreadInitThunk [0x0x7ffcd4147374+20]\n\tRtlUserThreadStart [0x0x7ffcd4dfcc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_home.py\", line 49, in login_to_home\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 33, in login\n    self.enter_password(password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 20, in enter_password\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入密码\"]', password)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 70, in enter_text\n    element.clear()  # 清空文本框\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 154, in clear\n    self._execute(Command.CLEAR_ELEMENT)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1755260185955, "stop": 1755260194898}], "start": 1755260185955, "stop": 1755260195154}