{"uuid": "195658f1-78c6-4165-b682-e456eca5cc50", "children": ["95181851-3719-47aa-a8e7-fb7d2b111e70"], "befores": [{"name": "login_to_psi", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff699f36f65+78965]\n\tGetHandleVerifier [0x0x7ff699f36fc0+79056]\n\t(No symbol) [0x0x7ff699cc9dda]\n\t(No symbol) [0x0x7ff699ca20d1]\n\t(No symbol) [0x0x7ff699d4ff4e]\n\t(No symbol) [0x0x7ff699d706cd]\n\t(No symbol) [0x0x7ff699d48443]\n\t(No symbol) [0x0x7ff699d11311]\n\t(No symbol) [0x0x7ff699d120a3]\n\tGetHandleVerifier [0x0x7ff69a1ee26d+2926461]\n\tGetHandleVerifier [0x0x7ff69a1e8993+2903715]\n\tGetHandleVerifier [0x0x7ff69a206aed+3026941]\n\tGetHandleVerifier [0x0x7ff699f516fe+187406]\n\tGetHandleVerifier [0x0x7ff699f596ef+220159]\n\tGetHandleVerifier [0x0x7ff699f3faf4+114692]\n\tGetHandleVerifier [0x0x7ff699f3fca9+115129]\n\tGetHandleVerifier [0x0x7ff699f264d8+10728]\n\tBaseThreadInitThunk [0x0x7ffff5547374+20]\n\tRtlUserThreadStart [0x0x7ffff5f9cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_psi.py\", line 48, in login_to_psi\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1755507829056, "stop": 1755507833381}], "start": 1755507829056, "stop": 1755507833435}