{"uuid": "6e73dcef-6e4b-409e-b48c-65d8e5661f63", "children": ["90484c99-6072-4627-bff6-e4786c00d38e"], "befores": [{"name": "login_to_affairs", "status": "passed", "start": 1754385085477, "stop": 1754385093661}], "afters": [{"name": "login_to_affairs::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_affairs.py\", line 36, in login_to_affairs\n    safe_quit(driver)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 49, in safe_quit\n    driver.quit()  # 尝试正常关闭浏览器\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 188, in quit\n    super().quit()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 589, in quit\n    self.execute(Command.QUIT)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 445, in request\n    self.endheaders()\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 1037, in _send_output\n    self.send(msg)\n  File \"D:\\Program Files\\Python310\\lib\\http\\client.py\", line 975, in send\n    self.connect()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 276, in connect\n    self.sock = self._new_conn()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\connection.py\", line 198, in _new_conn\n    sock = connection.create_connection(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\urllib3\\util\\connection.py\", line 73, in create_connection\n    sock.connect(sa)\n"}, "start": 1754385100157, "stop": 1754385112357}], "start": 1754385085477, "stop": 1754385112357}