{"uuid": "c959809f-014d-4ea4-934f-c8fe15ee2a77", "children": ["b10448c1-0f09-4325-93cd-b2b380925ec3"], "befores": [{"name": "login_to_psi", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff66a0c6f65+78965]\n\tGetHandleVerifier [0x0x7ff66a0c6fc0+79056]\n\t(No symbol) [0x0x7ff669e59dda]\n\t(No symbol) [0x0x7ff669e320d1]\n\t(No symbol) [0x0x7ff669edff4e]\n\t(No symbol) [0x0x7ff669f006cd]\n\t(No symbol) [0x0x7ff669ed8443]\n\t(No symbol) [0x0x7ff669ea1311]\n\t(No symbol) [0x0x7ff669ea20a3]\n\tGetHandleVerifier [0x0x7ff66a37e26d+2926461]\n\tGetHandleVerifier [0x0x7ff66a378993+2903715]\n\tGetHandleVerifier [0x0x7ff66a396aed+3026941]\n\tGetHandleVerifier [0x0x7ff66a0e16fe+187406]\n\tGetHandleVerifier [0x0x7ff66a0e96ef+220159]\n\tGetHandleVerifier [0x0x7ff66a0cfaf4+114692]\n\tGetHandleVerifier [0x0x7ff66a0cfca9+115129]\n\tGetHandleVerifier [0x0x7ff66a0b64d8+10728]\n\tBaseThreadInitThunk [0x0x7ffff5547374+20]\n\tRtlUserThreadStart [0x0x7ffff5f9cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_psi.py\", line 49, in login_to_psi\n    page.login(date_driver.username, date_driver.password, date_driver.planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 32, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 16, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1755594844054, "stop": 1755594845908}], "start": 1755594844054, "stop": 1755594846064}