{"uuid": "19bcb666-8f74-4962-85f2-16f4f47e8a5f", "children": ["c53dfa1c-eaae-4948-b318-11a64b9db750"], "befores": [{"name": "login_to_affairs", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=137.0.7151.69)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff714c26f65+78965]\n\tGetHandleVerifier [0x0x7ff714c26fc0+79056]\n\t(No symbol) [0x0x7ff7149b9dda]\n\t(No symbol) [0x0x7ff7149920d1]\n\t(No symbol) [0x0x7ff714a3ff4e]\n\t(No symbol) [0x0x7ff714a606cd]\n\t(No symbol) [0x0x7ff714a38443]\n\t(No symbol) [0x0x7ff714a01311]\n\t(No symbol) [0x0x7ff714a020a3]\n\tGetHandleVerifier [0x0x7ff714ede26d+2926461]\n\tGetHandleVerifier [0x0x7ff714ed8993+2903715]\n\tGetHandleVerifier [0x0x7ff714ef6aed+3026941]\n\tGetHandleVerifier [0x0x7ff714c416fe+187406]\n\tGetHandleVerifier [0x0x7ff714c496ef+220159]\n\tGetHandleVerifier [0x0x7ff714c2faf4+114692]\n\tGetHandleVerifier [0x0x7ff714c2fca9+115129]\n\tGetHandleVerifier [0x0x7ff714c164d8+10728]\n\tBaseThreadInitThunk [0x0x7ff992b87374+20]\n\tRtlUserThreadStart [0x0x7ff99357cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_affairs.py\", line 31, in login_to_affairs\n    page.login(DateDriver().username, DateDriver().password, DateDriver().planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 30, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\itemsPage\\login_page.py\", line 14, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 66, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754301529423, "stop": 1754301532088}], "start": 1754301529423, "stop": 1754301532194}